name: Build Our AMI 
run-name: ${{ github.actor }} is building AMI
on: 
  push:
    branches:
      - main
jobs:
  BuildMyAppContainerImage:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Does this work?"
      - name: Setup Code
        uses: actions/checkout@v4
      - name: Check that checkout worked
        run: ls -lh
      - name: Get Packer
        run: |
          "echo getting: wget https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_linux_amd64.zip"
          wget https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_linux_amd64.zip
          ls -lh packer_1.7.3_linux_amd64.zip
          unzip packer_1.7.3_linux_amd64.zip
          sudo mv packer /usr/local/bin
          packer --version
          # sudo apt install -y packer
      - name: Build Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          packer init .
          packer build my_app_ami.pkr.hcl
      
